### ISSUE TITLE
Process d'inscription

### ISSUE THREAD

**Issue by hanniju** [pciavald/.base#10]
Via un pop up :
> Pré-remplir à partir de la liste des participants ?
> Formulaire : nom, prénom, pseudo, mail, thèmes, autre + photo
> Entrée Onename
> Indiquer le chemin vers onename dans un nouvel onglet
> Expliquer pourquoi onename

![screen shot 2016-06-02 at 18 43 38](https://cloud.githubusercontent.com/assets/5124498/15753294/94ac5944-28f2-11e6-83c5-5c117daf5f4a.png)

**Comment by pciavald** [comment]
@aarmand some help here : 
http://stackoverflow.com/questions/32284412/meteor-accounts-custom-login-page

**Comment by hanniju** [comment]
- [ ] End of the process : vers "pages base"
