### ISSUE TITLE
page base

### ISSUE THREAD

**Issue by haniju** [pciavald/.base#13]
Sur cette page, on trouve l'ensemble des ressources postées, avec des options de filtrage.
(Options incertaines : 

> La page base est également le point d'entrée p
> Aussi, les ressources sont pre-filtrées en fonction du contexte d'entré.)

ORDRE DE CLASSEMENT DE BASE : Plus récent > plus vieux
Les 2 types de filtrage :  
Par type de contenu : 

> bingo board
> Compte-rendu
> Scenario / profil
> Element visuel
> Tutoriel
> Concept de jeu
> Prototype/sprint

Par mode d'édition : 

> Consulter
> Ajout contenu
> Ajout feedback

**Comment by hanniju** [comment]
![screen shot 2016-06-01 at 12 04 54](https://cloud.githubusercontent.com/assets/5124498/15705924/7b9097ec-27f1-11e6-89ed-e47bfef72a38.png)
Via un bandeau de picto ?

Animation des boutons : 
ON : 
![screen shot 2016-06-01 at 11 58 53](https://cloud.githubusercontent.com/assets/5124498/15705940/904741ae-27f1-11e6-96d8-975b4279a9e9.png)

OFF : 
![screen shot 2016-06-01 at 11 58 46](https://cloud.githubusercontent.com/assets/5124498/15705945/959d4860-27f1-11e6-9978-cd1b3d343d13.png)

**Comment by hanniju** [comment]
Mockup de la page base:
![screen shot 2016-06-05 at 18 46 16](https://cloud.githubusercontent.com/assets/5124498/15806901/fa6cf564-2b4e-11e6-8579-af6bde92e254.png)

Highlights : 
![screen shot 2016-06-05 at 18 53 04](https://cloud.githubusercontent.com/assets/5124498/15806902/fbf47ede-2b4e-11e6-8bcf-06b571aea63b.png)
![screen shot 2016-06-05 at 18 49 26](https://cloud.githubusercontent.com/assets/5124498/15806903/fc0e5e26-2b4e-11e6-963f-fe0beceb54dc.png)
![screen shot 2016-06-05 at 18 48 23](https://cloud.githubusercontent.com/assets/5124498/15806904/fc0f7e82-2b4e-11e6-8c28-03dd2dd89650.png)
![screen shot 2016-06-05 at 18 47 58](https://cloud.githubusercontent.com/assets/5124498/15806905/fc1576d4-2b4e-11e6-8370-4f72e2238614.png)
