### ISSUE TITLE
page ressource

### ISSUE THREAD

**Issue by haniju** [pciavald/.base#9]
- [x] 1 Tester le modèle de page bandeau avec les visuels (dossier public/bandeaux)
  ![screen shot 2016-05-20 at 15 02 55](https://cloud.githubusercontent.com/assets/5124498/15658055/2481205a-26b8-11e6-80ad-ec68d31cadab.png)
  version réduite ci-dessous :
  ![screen shot 2016-05-20 at 15 02 41](https://cloud.githubusercontent.com/assets/5124498/15658054/247fc7c8-26b8-11e6-9dac-ed745ae623ba.png)
- [x] 2 Passer sur un format de mise en page type :
  ![screen shot 2016-06-05 at 20 24 45](https://cloud.githubusercontent.com/assets/5124498/15807333/9d474b7a-2b5b-11e6-98f3-5ae0b402cb88.png)
- [ ] 3
- [ ] pre-remplir les champs du formulaire avec un exemple de contenu
  ![screen shot 2016-06-05 at 20 19 48](https://cloud.githubusercontent.com/assets/5124498/15807337/b86b6c56-2b5b-11e6-8b56-8c25c7c48984.png)
- [x] 4 Pour le feedback :
  voire issue : process et pages feedback
- [x] 5 PAGE ajout de resources : Ajouter les catégories : "description" & "lien avec le programme"
- [x] 6 Créer les catégories suivantes : Comptes-rendus / Tutoriels / Visuels / prototypes
  Inclure les détails de la description en haut de page

**Comment by pciavald** [comment]
I'll do the 4 and 5 for this issue

**Comment by hanniju** [comment]
Feedback page ajout de ressource : 

- [ ] Prévoir plus de marges 
- [ ] Rapprocher les pictos
- [ ] passer sur le même genre de grille que celle du formulaire d'inscription ?
- [ ] prévoir la possibilité d'uploader les images ? (peut-être meme à l'ext)
